### ISSUE TITLE
Only a small part of docs is generated

### ISSUE THREAD

**Issue by trikko** [dlang/ddox#246]
Using ddox with [parserino](https://github.com/trikko/parserino) only a small part of docs is generated for `struct Document`, not sure why. It sounds like a bug. I can see all the methods inside `docs.json`.

**Comment by trikko** [comment]
Ok, got it. It doesn't escape tags inside docs, is this a feature? A comment like this make a mess:
```d
/// The <body> tag content
```
This fix the problem and show all missing methods
```d
/// The `<body>` tag content
```

**Comment by WebFreak001** [comment]
since HTML escaping is not really part of DDOC and in fact is actually how you implement advanced outputs in HTML DDOC macros, I don't think preventing the user from messing up the HTML like this would be scope of ddox.

So since outputting raw HTML is a feature and covering all possible kinds of breaking content would be quite out of scope, I'm closing this as wont-fix

Note that adding a special case for `<body>` would be relatively useless imo, it's rare you even see that in docs
